version: '3'
services:
  bloom-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: bloomz-api:latest
    container_name: bloomz-api-container
    restart: always
    ports:
      - "7862:7862"
      - "7863:7863"