version: '3'
services:
  bloom-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: bloomz-api:latest
    container_name: bloomz-api-container
    restart: always
    ports:
      - "7862:7862"
      - "7863:7863"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: nvidia-smi
#    command: nvidia-smi
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: [ '1', '2', '3' ]
#              capabilities: [ gpu ]