version: '3'
services:
  bloom-mt-inference:
    build:
      context: .
      dockerfile: Dockerfile
#    runtime: nvidia
    image: bloom-mt-api-latest
    container_name: bloom-mt-api-container
    restart: always
    ports:
      - "7862:7862"
      - "7863:7863"
    volumes:
      - ../logs:/src/logs/
#      - ../transformer-models/mt0-xxl-mt:/src/mt0-xxl-mt/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: nvidia-smi