version: '3'
services:
  bloom-xp3mt-inference-cache:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: bloom-xp3mt-api-latest-cache
    container_name: bloom-xp3mt-api-container-cache
    restart: always
    ports:
      - "7865:7865"
      - "7867:7867"
    volumes:
      - ../logs:/src/logs/
      - ../bloom-models/bloom-mt0-xxl-mt-hf-cache/HF_cache:/cos/HF_cache/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility