version: '3'
services:
  bloom-xp3mt-inference-debug:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: bloom-xp3mt-api-latest-debug
    container_name: bloom-xp3mt-api-container-debug
    restart: always
    ports:
      - "7862:7862"
      - "7863:7863"
    volumes:
      - ../logs:/src/logs/
      - ../bloom-models/bloom-mt0-xxl-mt-hf-cache/HF_cache:/cos/HF_cache/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility